name: Build Linux 86_64
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install libcurl
        run: |
          sudo apt-get update
          sudo apt-get install libcurl3-dev

      - name: Run build
        run: ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-native-build
          path: sample/build/bin
