name: Download libcrypt
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Where is libcrypt
        run: whereis libcrypt.so.1
      - name: Upload libcrypt
        uses: actions/upload-artifact@v3
        with:
          name: kotlin-native-arm-build
          path: lib/x86_64-linux-gnu/libcrypt.so.1

  
